### ISSUE TITLE
Account compromized warning after sending DM to 6 user

### ISSUE THREAD

**Issue by nicoirm** [hbollon/IGopher#13]
![Screenshot from 2021-09-13 12-20-25](https://user-images.githubusercontent.com/43660600/133032502-c2c4047f-cb4f-4401-a0a6-38a8a705049f.png)

hi, i am using latest TUI release for amd64, after scrapping, the bot successfully send to 6 user, then failed, instagram give compromized warning page right after login. 

{"level":"info","msg":"Downloading and installing dependencies...","time":"2021-09-13T04:41:13Z"}
{"level":"info","msg":"Connecting to Instagram account...","time":"2021-09-13T04:41:36Z"}
{"level":"info","msg":"Cookies validation button not found, skipping.","time":"2021-09-13T04:41:55Z"}
{"level":"info","msg":"Login button not found, skipping.","time":"2021-09-13T04:42:08Z"}
{"level":"info","msg":"Login Successful!","time":"2021-09-13T04:42:29Z"}
{"level":"info","msg":"Fetching users from users followers...","time":"2021-09-13T04:42:29Z"}
{"level":"info","msg":"Send message to xxxxxx...","time":"2021-09-13T04:52:38Z"}
{"level":"info","msg":"Message successfully sent!","time":"2021-09-13T04:56:34Z"}
{"level":"info","msg":"Send message to xxxxxx...","time":"2021-09-13T04:56:34Z"}
{"level":"info","msg":"Message successfully sent!","time":"2021-09-13T05:00:36Z"}
{"level":"info","msg":"Send message to xxxxxx...","time":"2021-09-13T05:00:36Z"}
{"level":"info","msg":"Message successfully sent!","time":"2021-09-13T05:04:32Z"}
{"level":"info","msg":"Send message to xxxxxx...","time":"2021-09-13T05:04:32Z"}
{"level":"info","msg":"Message successfully sent!","time":"2021-09-13T05:08:36Z"}
{"level":"info","msg":"Send message to xxxxxx...","time":"2021-09-13T05:08:36Z"}
{"level":"info","msg":"Message successfully sent!","time":"2021-09-13T05:12:31Z"}
{"level":"info","msg":"Send message to xxxxxx..","time":"2021-09-13T05:12:31Z"}
{"level":"warning","msg":"Failed to find process: %!s(\u003cnil\u003e)\n. The pid must be outdated.","time":"2021-09-13T05:12:59Z"}
{"level":"info","msg":"Delete outdated pid file and continue.","time":"2021-09-13T05:12:59Z"}
{"level":"info","msg":"Downloading and installing dependencies...","time":"2021-09-13T05:12:59Z"}
{"level":"info","msg":"Connecting to Instagram account...","time":"2021-09-13T05:13:26Z"}
{"level":"info","msg":"Cookies validation button not found, skipping.","time":"2021-09-13T05:13:44Z"}
{"level":"info","msg":"Login button not found, skipping.","time":"2021-09-13T05:13:58Z"}
{"level":"warning","msg":"Instagram does not ask for informations saving, the login process may have failed.","time":"2021-09-13T05:14:20Z"}
{"level":"info","msg":"Fetching users from users followers...","time":"2021-09-13T05:14:20Z"}
{"level":"info","msg":"IGopher's ressources successfully cleared!","time":"2021-09-13T05:14:45Z"}
{"level":"fatal","msg":"Failed users fetching: Empty users result","time":"2021-09-13T05:14:45Z"}

**Comment by hbollon** [comment]
Hi, can you share me your `config.yaml` file? (be careful to remove all secrets)

Unfortunately, I can't do anything directly to fix this issue... I work continuously to make the bot as little detectable as possible.
Anyways, I heavily advice you to use a proxy with IGopher (it support it since the last update) or any others bot and if possible a residential one.

**Comment by nicoirm** [comment]
account:
  username: xxxxxx
  password: yyyyyy
scrapper:
  src_accounts:
  - jagadiri_id
  - acainsurance
  fetch_quantity: 500
auto_dm:
  dm_templates:
  - xxxxxxx
  greeting:
    template: Hello
    activated: false
  activated: true
quotas:
  dm_per_day: 120
  dm_per_hour: 40
  activated: true
schedule:
  begin_at: "03:00"
  end_at: "13:00"
  activated: true
blacklist:
  activated: true
webdriver:
  proxy:
    ip: ""
    port: 8080
    username: ""
    password: ""
    auth: false
    activated: false


Hi Hbollon, Sorry for late reply, That is my config file, and yes i put the bot on my VM in datacenter, that might be the issue. Thanks

**Comment by hbollon** [comment]
Ok so it's totally normal, you doesn't run it with any proxy and so IGopher used the Datacenter's IP.
I really advice you to, at least, run IGopher on a decentralized computer or use a residential or high quality proxy with IGopher. :smile: 
Furthermore, 40 DM by hour seems a little bit high with actual Instagram policy :disappointed_relieved:
