### ISSUE TITLE
TUI HUGE ERROR MESSAGE AFTER DEPENDENCIES DOWNLOAD

### ISSUE THREAD

**Issue by GHST-13** [hbollon/IGopher#21]
**Describe the bug**
After launching on TUI, once dependencies are downloaded, the entire prompt closes and then.. nothing. at all.

on second try, i get a huge error message. 
ERRO[0071] unknown error - 33: Unable to create session from {
  "desiredCapabilities": {
    "browserName": "chrome",
    "chromeOptions": {
      "binary": ".\\lib\\chrome-win\\chrome.exe",
      "args": [
        "--incognito",
        "--disable-extensions",
        "--disable-infobars",
        "--disable-dev-shm-usage",
        "--no-sandbox",
        "--window-size=360,740"

**Comment by hbollon** [comment]
Issue surely related with #18

**Comment by hbollon** [comment]
Closed since this must be related to Java version incompatibility and it was fixed in #18 
If you still have issues with the TUI version please open a new issue
