### ISSUE TITLE
Chromium error

### ISSUE THREAD

**Issue by stelioskoul** [hbollon/IGopher#24]
Hey, im running the app on MacOs and every time i receive an error that says:

unknown error - 33: session not created: This version of ChromeDriver only supports Chrome version 95 Current browser version is 100.0.4851.0 with binary path ./lib/chrome-mac/Chromium.app/Contents/MacOS/Chromium (Driver info: chromedriver=95.0.4607.0 (d30668754e28963f133f4b00238e05f783f953c2-refs/heads/master@{#911926}),platform=Mac OS X 12.0.1 arm64) (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 26.01 seconds Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53' System info: host: 'stelioss-mbp', ip: '2a02:587:c42e:8100:6910:1587:6814:adc0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.10' Driver info: driver.version: unknown

Its something about chromium so could anybody help me fix this issue?
thanks

**Comment by hbollon** [comment]
Hi!
I just released a new version of IGopher (v0.4.0), can you retry with it?
Delete all current IGopher's stuff before

**Comment by goldenmommy** [comment]
I'm on version 0.40 and I get the following error:

ERRO[0036] unknown error - 33: Unable to create session from {
  "desiredCapabilities": {
    "browserName": "chrome",
    "chromeOptions": {
      "binary": ".\u002flib\u002fchrome-mac\u002fChromium.app\u002fContents\u002fMacOS\u002fChromium",
      "args": [
        "--incognito",
        "--disable-extensions",
        "--disable-infobars",
        "--disable-dev-shm-usage",
        "--no-sandbox",
        "--window-size=360,740"
      ],
      "mobileEmulation": {
        "deviceMetrics": {
          "width": 360,
          "height": 740,
          "pixelRatio": 2.05
        },
        "userAgent": "Mozilla\u002f5.0 (Linux; Android 8.0.0; SM-G960F Build\u002fR16NW) AppleWebKit\u002f537.36 (KHTML, like Gecko) Chrome\u002f64.0.3282.137 Mobile Safari\u002f537.36"
      },
      "w3c": false
    },
    "goog:chromeOptions": {
      "binary": ".\u002flib\u002fchrome-mac\u002fChromium.app\u002fContents\u002fMacOS\u002fChromium",
      "args": [
        "--incognito",
        "--disable-extensions",
        "--disable-infobars",
        "--disable-dev-shm-usage",
        "--no-sandbox",
        "--window-size=360,740"
      ],
      "mobileEmulation": {
        "deviceMetrics": {
          "width": 360,
          "height": 740,
          "pixelRatio": 2.05
        },
        "userAgent": "Mozilla\u002f5.0 (Linux; Android 8.0.0; SM-G960F Build\u002fR16NW) AppleWebKit\u002f537.36 (KHTML, like Gecko) Chrome\u002f64.0.3282.137 Mobile Safari\u002f537.36"
      },
      "w3c": false
    }
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "chrome",
        "goog:chromeOptions": {
          "binary": ".\u002flib\u002fchrome-mac\u002fChromium.app\u002fContents\u002fMacOS\u002fChromium",
          "args": [
            "--incognito",
            "--disable-extensions",
            "--disable-infobars",
            "--disable-dev-shm-usage",
            "--no-sandbox",
            "--window-size=360,740"
          ],
          "mobileEmulation": {
            "deviceMetrics": {
              "width": 360,
              "height": 740,
              "pixelRatio": 2.05
            },
            "userAgent": "Mozilla\u002f5.0 (Linux; Android 8.0.0; SM-G960F Build\u002fR16NW) AppleWebKit\u002f537.36 (KHTML, like Gecko) Chrome\u002f64.0.3282.137 Mobile Safari\u002f537.36"
          },
          "w3c": false
        }
      }
    ]
  }
}
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'miless-MacBook-Pro.local', ip: 'fe80:0:0:0:10cb:3b77:2dd0:6dea%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.5', java.version: '16.0.1'
Driver info: driver.version: unknown  function=InitChromeWebDriver line=153
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c8 pc=0x14f7d91]

goroutine 85 [running]:
github.com/hbollon/igopher.launchBot({0x1722378, 0xc00030f600})
	/home/hbollon/git/igopher/bot.go:282 +0xb71
created by github.com/hbollon/igopher.(*MessageIn).launchDmBotCallback
	/home/hbollon/git/igopher/gui_messages.go:264 +0xf1

**Comment by hbollon** [comment]
Hi @goldenmommy 
Glad to hear that you have solved your issue 🙂
Indeed, IGopher currently use **Selenium 3** which isn't compatible with JRE < 11.
However, you should run it without any trouble on Java 8 or 11.

I'm closing this issue, if you encounter another issue don't hesitate to reopen a new one 😉
