### ISSUE TITLE
runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by ExoticBeing888** [hbollon/IGopher#30]
**Describe the bug**
runtime error: index out of range [0] with length 0 pops up after initiating the first user to send a message.

**To Reproduce**

**Expected behavior**
I just want to run the bot, scrape usernames then DM them

**Screenshots**

**Error output**
runtime error: index out of range [0] with length 0

**Desktop (please complete the following information):**
 Windows

**Additional context**

**Comment by hbollon** [comment]
Hi @ExoticBeing888 
It's fixed on the new relese [v0.4.2](https://github.com/hbollon/IGopher/releases/tag/v0.4.2)
