### ISSUE TITLE
Likes photos

### ISSUE THREAD

**Issue by zsvendo** [hbollon/IGopher#4]
Create likes by photos, by hashtags

**Comment by hbollon** [comment]
Hey! Thanks for your interest! :smile: 
Likes automation is definitely a planned feature! 
You can check IGopher roadmaps here : https://github.com/hbollon/IGopher/projects
For the moment, the priorities are: native proxy support, GUI improvements and some others high priority improvements/bug fix etc.
Nevertheless, the automation of followers / likes will come soon after, so stay turned! :wink:

**Comment by zsvendo** [comment]
???????????????

**Comment by hbollon** [comment]
As I told you previously, this feature is on the general roadmap but is not yet planned. 
I am currently working on others essential features such as native proxy support, running Igopher as background task, redesigning the GUI to a modern framework, etc. 

In addition, we have a [Code of Conduct](https://github.com/hbollon/IGopher/blob/master/CONTRIBUTING.md) that I invites you to consult, this kind of messages is not acceptable in an Open-Source project. A minimum of politeness when asking for something from volunteer work. 
I work alone on this project and I have other priority activities, however, if you want to work on your feature the repo is open to contributions.  

Anyways, you can follow IGopher roadmaps [here](https://github.com/hbollon/IGopher/projects) which I keep updated with upcoming features, patchs and updates.
