### ISSUE TITLE
Doesnt work for me

### ISSUE THREAD

**Issue by mirko0704** [hbollon/IGopher#43]
hey i dont know why but i dont get it what im doing wrong.

first of all i can’t open it in the tui window and i don’t understand how to set up.
also it does nothing and shows this.
![image](https://user-images.githubusercontent.com/130871800/232254886-ffcea57e-4b73-46a6-b049-19c70175e225.jpg)

i wanted to ask if you could do a yt tutorial and explain everything? or dm me on instagram 
@mirko.lmo

**Comment by triantafylloskountardas** [comment]
same issue it opens a chromium instance and a terminal with the chromium instance target to data:,
