### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by f1-outsourcing** [hbollon/IGopher#47]
**Describe the bug**
after the browser private popup and log in, crashes the browser popup and then the application crashes

crashes also on the popup with the cookie statement.

**Desktop (please complete the following information):**
 - OS: windows 10 gui

**Error output**

<html>
<body>

info | astikit: worker is now waiting... | 2023-07-10T12:33:06+02:00
-- | -- | --
info | astikit: starting worker... | 2023-07-10T12:33:06+02:00
fatal | Log in button not found: Timed out : element not found | 2023-07-10T11:58:39+02:00
info | IGopher's ressources successfully cleared! | 2023-07-10T11:58:39+02:00
info | Login button not found, skipping. | 2023-07-10T11:58:20+02:00
info | Cookies validation button not found, skipping. | 2023-07-10T11:58:05+02:00
info | Connecting to Instagram account... | 2023-07-10T11:57:50+02:00
info | All dependencies are already installed, skipping. | 2023-07-10T11:57:47+02:00
info | Downloading and installing dependencies... | 2023-07-10T11:57:45+02:00
info | astikit: worker is now waiting... | 2023-07-10T11:57:24+02:00
info | astikit: starting worker... | 2023-07-10T11:57:23+02:00
fatal | Log in button not found: Timed out : element not found | 2023-07-10T11:55:53+02:00
info | IGopher's ressources successfully cleared! | 2023-07-10T11:55:53+02:00

</body>
</html>

**Comment by DaddyAbadi** [comment]
Any luck?

**Comment by f1-outsourcing** [comment]
I skipped using this and went for a browser plugin
DMfox - IG DM Bot & Bulk Message Sender (if I remember correctly)
