### ISSUE TITLE
App closes immediately after opening up

### ISSUE THREAD

**Issue by gabrielboeker** [hbollon/IGopher#49]
**Describe the bug**
App opens up and closes immediately

**To Reproduce**
1. downloaded and installed latest stable version for macOS on ARM64 
2. open up the app via right click → open
3. App opens up and closes immediately

**Expected behavior**
App opens up and displays some sort of GUI

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.4.1
 - IGopher 0.4.2

**Comment by gabrielboeker** [comment]
apparently there is no m1 compatibility

**Comment by thacreatorr** [comment]
so how can i resolve this issue
