### ISSUE TITLE
Driver info: driver version: unknown

### ISSUE THREAD

**Issue by crossoveranx** [hbollon/IGopher#7]
**Describe the bug**
Launch via the GUI - selenium launches 3 chromium windows however does nothing else with simply data; in the address bar. Seems stuck. I can confirm I have Java and Java JDK installed 

**Expected behavior**
Expected that selenium navigates to instagram and begins messaging users.

**Screenshots**
![Screenshot from 2020-09-12 20-30-15](https://user-images.githubusercontent.com/19821370/123658707-42772100-d832-11eb-944b-69af970fab35.png)

**Error output**
Driver info: driver version: unknown

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by hbollon** [comment]
Hi!
I'm also on Ubuntu 20.04 and I don't have any issues.
I think I know what your problem was, atm, the download of the necessary dependencies is done when user launch the bot via the GUI (on "Launch Bot" button click). 
The problem is that there is no download tracking interface yet in this GUI (and since there is around 200mb to download it may take a while before the bot actually starts).

This is an important problem that I'm going to solve, a rather big update is coming (Changelog: https://github.com/hbollon/IGopher/projects/3) unfortunately the migration to vuejs / typescript still requires a little time and I have a lot of work on the side...

So that I can confirm that this is the problem you have encountered I will need the log file located in the corresponding subfolder in the installation directory of IGopher.
In the meantime, you can run the GUI through the terminal, there is a download tracking interface in stdout. (just locate your bash in the IGopher directory and run `./IGopher`)

**Comment by crossoveranx** [comment]
[logs.log](https://github.com/hbollon/IGopher/files/6732242/logs.log)

Here's the requested log file/ The latest error when running through the terminal is:

INFO[0024] Connecting to Instagram account...            function=connectToInstagramWebDriver line=16
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0x9aa3e2]

goroutine 290 [running]:
github.com/hbollon/igopher.(*IGopher).connectToInstagramWebDriver(0x59b3040)
	/home/hbollon/Documents/Projets/igopher/actions.go:18 +0xa2
github.com/hbollon/igopher.(*IGopher).ConnectToInstagram(...)
	/home/hbollon/Documents/Projets/igopher/actions.go:12
github.com/hbollon/igopher.launchDmBot.func1(0xc0001d6020)
	/home/hbollon/Documents/Projets/igopher/bot.go:190 +0x1c5
created by github.com/hbollon/igopher.launchDmBot
	/home/hbollon/Documents/Projets/igopher/bot.go:184 +0x74d





 please let me know any additional questions

**Comment by hbollon** [comment]
Okay so according to your logs it's due to Selenium who does not manage to launch Chrome instance.
Can you, please, try to delete `lib/` sub-folder and launch IGopher through bash using : `./IGopher --loglevel=debug`

**Comment by crossoveranx** [comment]
Done - getting the same error as before:

INFO[0024] Connecting to Instagram account...            function=connectToInstagramWebDriver line=16
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0x9aa3e2]

goroutine 290 [running]:
github.com/hbollon/igopher.(*IGopher).connectToInstagramWebDriver(0x59b3040)
	/home/hbollon/Documents/Projets/igopher/actions.go:18 +0xa2
github.com/hbollon/igopher.(*IGopher).ConnectToInstagram(...)
	/home/hbollon/Documents/Projets/igopher/actions.go:12
github.com/hbollon/igopher.launchDmBot.func1(0xc0001d6020)
	/home/hbollon/Documents/Projets/igopher/bot.go:190 +0x1c5
created by github.com/hbollon/igopher.launchDmBot
	/home/hbollon/Documents/Projets/igopher/bot.go:184 +0x74d

**Comment by hbollon** [comment]
Can I have the full log file now please?

**Comment by crossoveranx** [comment]
Whoops, sorry. Here is the log file I provided previously and then from the terminal with username/password removed:

[logs.log](https://github.com/hbollon/IGopher/files/6732877/logs.log)
[logfromterminal.log](https://github.com/hbollon/IGopher/files/6732885/logfromterminal.log)

**Comment by hbollon** [comment]
I deleted you message because your password still in the file
It makes me think that even in debug I should avoid logging this

**Comment by hbollon** [comment]
Okay so can you:
- Send me a screenshot of the `lib/` sub-folder
- Check if `lib/chrome-linux/chrome` executable exists and if it's run well with `./chrome`
- Check if it has executable right (if not run `chmod +x ./chrome` and retry to launch the bot)

**Comment by crossoveranx** [comment]
![screenshotlib](https://user-images.githubusercontent.com/19821370/123794193-ddc7cf00-d8e2-11eb-9d44-dca8ef618c06.png)

Executable exists and runs correctly as well as having executable rights. Tried the change of permissions you suggested and same error

**Comment by hbollon** [comment]
Hey! Sorry for the delay.
I will investigate on your issue in the weekend

**Comment by crossoveranx** [comment]
Hi! Yes - latest version
